version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: "postgres_db"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-networks
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - prisma-networks
  dev:
    build: .
    container_name: "express-node"
    restart: "always"
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - prisma-networks

volumes:
  postgres_data:

networks:
  prisma-networks:
    driver: bridge